from os import getenv

ACCESS_TOKEN_EXPIRE_MINUTES: int = 30   # 30분
REFRESH_TOKEN_EXPIRE_MINUTES: int = 60 * 24 * 7     # 7일
ALGORITH: str = "HS256"
JWT_SECRET_KEY: str = getenv('JWT_SECRET_KEY')
JWT_REFRESH_SECRET_KEY: str = getenv('JWT_REFRESH_SECRET_KEY')